//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeaRoxy.Windows.WPFClient {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class MultiInstance : global::System.Configuration.ApplicationSettingsBase {
        
        private static MultiInstance defaultInstance = ((MultiInstance)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MultiInstance())));
        
        public static MultiInstance Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastArgs {
            get {
                return ((string)(this["LastArgs"]));
            }
            set {
                this["LastArgs"] = value;
            }
        }
    }
}
