//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeaRoxy.Windows.WPFClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeaRoxy.Windows.WPFClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SmartProfile xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HttpRules /&gt;
        ///  &lt;DirectRules /&gt;
        ///  &lt;AntiDnsPoisoningRule /&gt;
        ///  &lt;AntiBlockPageRule /&gt;
        ///  &lt;DirectTimeout&gt;60&lt;/DirectTimeout&gt;
        ///  &lt;IsHttpSupported&gt;false&lt;/IsHttpSupported&gt;
        ///  &lt;IsHttpsSupported&gt;false&lt;/IsHttpsSupported&gt;
        ///  &lt;IsSocksSupported&gt;false&lt;/IsSocksSupported&gt;
        ///  &lt;HttpBlockPageDetection&gt;false&lt;/HttpBlockPageDetection&gt;
        ///  &lt;DnsPoisoningDetection&gt;false&lt;/DnsPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smart {
            get {
                return ResourceManager.GetString("Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SmartProfile xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HttpRules /&gt;
        ///  &lt;DirectRules /&gt;
        ///  &lt;AntiDnsPoisoningRule /&gt;
        ///  &lt;AntiBlockPageRule /&gt;
        ///  &lt;DirectTimeout&gt;60&lt;/DirectTimeout&gt;
        ///  &lt;IsHttpSupported&gt;false&lt;/IsHttpSupported&gt;
        ///  &lt;IsHttpsSupported&gt;false&lt;/IsHttpsSupported&gt;
        ///  &lt;IsSocksSupported&gt;false&lt;/IsSocksSupported&gt;
        ///  &lt;HttpBlockPageDetection&gt;false&lt;/HttpBlockPageDetection&gt;
        ///  &lt;DnsPoisoningDetection&gt;false&lt;/DnsPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smart_AE {
            get {
                return ResourceManager.GetString("Smart_AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SmartProfile xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HttpRules&gt;
        ///    &lt;string&gt;* | *google.c*&lt;/string&gt;
        ///    &lt;string&gt;* | *facebook.c*&lt;/string&gt;
        ///    &lt;string&gt;* | *youtube.c*&lt;/string&gt;
        ///    &lt;string&gt;* | *twitter.c*&lt;/string&gt;
        ///  &lt;/HttpRules&gt;
        ///  &lt;DirectRules&gt;
        ///    &lt;string&gt;* | *google.c*:*&lt;/string&gt;
        ///    &lt;string&gt;* | *facebook.c*:*&lt;/string&gt;
        ///    &lt;string&gt;* | *youtube.c*:*&lt;/string&gt;
        ///    &lt;string&gt;* | *twitter.c*:*&lt;/string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smart_CH {
            get {
                return ResourceManager.GetString("Smart_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SmartProfile xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HttpRules&gt;
        ///    &lt;string&gt;* | *google.c*&lt;/string&gt;
        ///    &lt;string&gt;* | *facebook.c*&lt;/string&gt;
        ///    &lt;string&gt;* | *youtube.c*&lt;/string&gt;
        ///    &lt;string&gt;* | *twitter.c*&lt;/string&gt;
        ///    &lt;string&gt;* | *paypal*&lt;/string&gt;
        ///    &lt;string&gt;* | *amazon.c*&lt;/string&gt;
        ///  &lt;/HttpRules&gt;
        ///  &lt;DirectRules&gt;
        ///    &lt;string&gt;* | *google.c*:*&lt;/string&gt;
        ///    &lt;string&gt;* | *facebook.c*:*&lt;/string&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smart_IR {
            get {
                return ResourceManager.GetString("Smart_IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SmartProfile xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HttpRules /&gt;
        ///  &lt;DirectRules /&gt;
        ///  &lt;AntiDnsPoisoningRule /&gt;
        ///  &lt;AntiBlockPageRule /&gt;
        ///  &lt;DirectTimeout&gt;60&lt;/DirectTimeout&gt;
        ///  &lt;IsHttpSupported&gt;false&lt;/IsHttpSupported&gt;
        ///  &lt;IsHttpsSupported&gt;false&lt;/IsHttpsSupported&gt;
        ///  &lt;IsSocksSupported&gt;false&lt;/IsSocksSupported&gt;
        ///  &lt;HttpBlockPageDetection&gt;false&lt;/HttpBlockPageDetection&gt;
        ///  &lt;DnsPoisoningDetection&gt;false&lt;/DnsPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smart_PK {
            get {
                return ResourceManager.GetString("Smart_PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SmartProfile xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HttpRules /&gt;
        ///  &lt;DirectRules /&gt;
        ///  &lt;AntiDnsPoisoningRule /&gt;
        ///  &lt;AntiBlockPageRule /&gt;
        ///  &lt;DirectTimeout&gt;60&lt;/DirectTimeout&gt;
        ///  &lt;IsHttpSupported&gt;false&lt;/IsHttpSupported&gt;
        ///  &lt;IsHttpsSupported&gt;false&lt;/IsHttpsSupported&gt;
        ///  &lt;IsSocksSupported&gt;false&lt;/IsSocksSupported&gt;
        ///  &lt;HttpBlockPageDetection&gt;false&lt;/HttpBlockPageDetection&gt;
        ///  &lt;DnsPoisoningDetection&gt;false&lt;/DnsPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smart_SA {
            get {
                return ResourceManager.GetString("Smart_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SmartProfile xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;HttpRules&gt;
        ///    &lt;string&gt;* | *youtube.c*&lt;/string&gt;
        ///    &lt;string&gt;* | *twitter.c*&lt;/string&gt;
        ///  &lt;/HttpRules&gt;
        ///  &lt;DirectRules&gt;
        ///    &lt;string&gt;* | *youtube.c*:*&lt;/string&gt;
        ///    &lt;string&gt;* | *twitter.c*:*&lt;/string&gt;
        ///  &lt;/DirectRules&gt;
        ///  &lt;AntiDnsPoisoningRule&gt;^195.175.254.*&lt;/AntiDnsPoisoningRule&gt;
        ///  &lt;AntiBlockPageRule /&gt;
        ///  &lt;DirectTimeout&gt;20&lt;/DirectTimeout&gt;
        ///  &lt;IsHttpS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smart_TR {
            get {
                return ResourceManager.GetString("Smart_TR", resourceCulture);
            }
        }
    }
}
